var fs = require('fs'),
    //MongoClient = require('mongodb').MongoClient,
    db;

fs.exists(__dirname + '/tmp', function (exists) {
    if (!exists) {
        console.log('Creating directory ' + __dirname + '/tmp');
        fs.mkdir(__dirname + '/tmp', function (err) {
            if (err) {
                console.log('Error creating ' + __dirname + '/tmp');
                process.exit(1);
            }
        })
    }
});

// Create the "uploads" folder if it doesn't exist
fs.exists(__dirname + '/uploads', function (exists) {
    if (!exists) {
        console.log('Creating directory ' + __dirname + '/uploads');
        fs.mkdir(__dirname + '/uploads', function (err) {
            if (err) {
                console.log('Error creating ' + __dirname + '/uploads');
                process.exit(1);
            }
        })
    }
});

// Connect to database
/*var url = "mongodb://localhost:27017/PictureFeed";
MongoClient.connect(url, { native_parser: true }, function (err, connection) {
    if (err) {
        console.log("Cannot connect to database " + url);
        process.exit(1);
    }
    db = connection;
});*/

exports.getImages = function (req, res, next) {
    var images = db.collection('images');

    images.find().sort({ _id: -1 }).limit(20).toArray(function (err, data) {
        if (err) {
            console.log(err);
            return next(err);
        }
        res.json(data);
    });
};

exports.addCahier = function (req, res, next) {

    console.log("upload cahier");

    var file = req.files.file,
        filePath = file.path,
//        fileName = file.name, file name passed by client. Not used here. We use the name auto-generated by Node
        lastIndex = filePath.lastIndexOf("/"),
        tmpFileName = filePath.substr(lastIndex + 1),
        image = req.body;
    //images = db.collection('images');
    var id = req.params.id;
    image.fileName = tmpFileName;

    
            fs.exists(__dirname + '/uploads/' + id, function (exists) {
                if (!exists) {
                    //console.log('Creating directory ' + __dirname + '/uploads/' + id);
                    fs.mkdir(__dirname + '/uploads/' + id, function (err) {
                        if (err) {
                            console.log('Error creating ' + __dirname + '/uploads/' + +id);
                        }
                        fs.readFile(filePath, function (err, data) {
                            // ...
                            var newPath = __dirname + "/uploads/" + id + "/" + file.name;
                            //console.log("newPath " + newPath);
                            fs.writeFile(newPath, data, function (err) {
                                fs.unlink(filePath, function (err) {
                                    if (err) throw err;
                                });
                            });
                        });
                    });
                }
                fs.readFile(filePath, function (err, data) {
                    // ...
                    var newPath = __dirname + "/uploads/" + id + "/" + file.name;
                    //console.log("newPath " + newPath);
                    fs.writeFile(newPath, data, function (err) {
                        fs.unlink(filePath, function (err) {
                            if (err) throw err;
                        });
                    });
                });
            });
            

    //console.log("id " + id);
    //console.log(tmpFileName);
    //console.log(image);
    //console.log(req);

    res.write("ok");
    res.end();

    /*images.insert(image, function (err, result) {
        if (err) {
            console.log(err);
            return next(err);
        }
        res.json(image);
    });*/

};

exports.addImage = function (req, res, next) {

    console.log("upload picture");

    var file = req.files.file,
        filePath = file.path,
//        fileName = file.name, file name passed by client. Not used here. We use the name auto-generated by Node
        lastIndex = filePath.lastIndexOf("/"),
        tmpFileName = filePath.substr(lastIndex + 1),
        image = req.body;
        //images = db.collection('images');
    var id = req.params.id;
    image.fileName = tmpFileName;
    fs.readFile(filePath, function (err, data) {
        // ...
        var newPath = __dirname + "/uploads/" + id + "/" + file.name;
        fs.writeFile(newPath, data, function (err) {
            fs.unlink(filePath, function (err) {
                if (err) throw err;
            });
        });
    });

    console.log("id " + id);
    console.log(tmpFileName);
    //console.log(req);

    res.write("ok");
    res.end();

    /*images.insert(image, function (err, result) {
        if (err) {
            console.log(err);
            return next(err);
        }
        res.json(image);
    });*/

};